const filterOptions = {
  type: ['all', 'movie', 'tv', 'ova', 'special', 'music'],
  status: ['all', 'finished_airing', 'currently_airing', 'not_yet_aired'],
  rated: ['all', 'g', 'pg', 'pg-13', 'r', 'r+', 'rx'],
  score: [
    'all',
    'appalling',
    'horrible',
    'very_bad',
    'bad',
    'average',
    'fine',
    'good',
    'very_good',
    'great',
    'masterpiece',
  ],
  season: ['all', 'spring', 'summer', 'fall', 'winter'],
  language: ['all', 'sub', 'dub', 'sub_dub'],
  sort: [
    'default',
    'recently_added',
    'recently_updated',
    'score',
    'name_az',
    'release_date',
    'most_watched',
  ],
  genres: [
    'action',
    'adventure',
    'cars',
    'comedy',
    'dementia',
    'demons',
    'mystery',
    'drama',
    'ecchi',
    'fantasy',
    'game',
    '',
    'historical',
    'horror',
    'kids',
    'magic',
    'martial_arts',
    'mecha',
    'music',
    'parody',
    'samurai',
    'romance',
    'school',
    'sci-fi',
    'shoujo',
    'shoujo_ai',
    'shounen',
    'shounen_ai',
    'space',
    'sports',
    'super_power',
    'vampire',
    '',
    '',
    'harem',
    'slice_of_life',
    'supernatural',
    'military',
    'police',
    'psychological',
    'thriller',
    'seinen',
    'josei',
    'isekai',
  ],
};

export default filterOptions;
